# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7a7aba45ec11b3b669459f7d1e6f97ef0f89529943eec36cba6f463497648f7bb809a8d590650f2b370d7305a71f0bf63971517dd623520b9c7e2d4b826c28

test:
  secret_key_base: 5f66dc7e6717a570b4a046a71ac27b99860e8a07e1b6f8b622f7644c0e27c4784c5a7dcedbf06fb2e4321edeb719e497f967ab514e51ce47e68e219353990c42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
